### ISSUE TITLE
moving and selecting images

### ISSUE THREAD

**Issue by fbarillon** [DIP-SEM/OpenBoard#18]
Using OB 1.3rc2 on Ubuntu 14.04 there is a lack of coherence when trying to move selected images, you can't move the image by clicking in the bounding box just drag to the library (witch is not a frequent use).
We should drag selected images by clicking in the bounding box and find another way to send objects in the library.

**Comment by freeheel3r** [comment]
Being able to drag and drop objects (well, just images really) to the library is an intentional feature, so that will be kept.
However, I changed the behavior when adding an image to the board: it is now dropped in an unselected state, so it can be moved around without having to first click somewhere else. (Commit 0491ce9)
So that should be a bit more intuitive.
